public class MemberWrapper {

        public Account member;
    

        public MemberWrapper(){
            this.member = new Account();
        }
    

    public class Member {          
        public String salutation;
        public String Name;
        public String middleName;
        public String lastName;
        public String nameLocal;
        public String primaryEmail;
        public String primaryLanguage;
        public String defaultEmail;
        public String defaultPhone;
        public String dedicatedAccountManager;
        public String dedicatedAccountManagerEmail;
        public String secondEmail;
        
        

    }
    }